// <auto-generated />
namespace Server.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Npgsql.EntityFrameworkCore.PostgreSQL.Metadata

[<DbContext(typeof<DomainModels.PalladrisContext>)>]
[<Migration("20210905020614_InitialCreate")>]
type InitialCreate() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "PalladrisTransaction"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "integer"
                    ).Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                Pairs =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "text"
                    )
                Provider =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "text"
                    )
                Price =
                    table.Column<double>(
                        nullable = false
                        ,``type`` = "double precision"
                    )
                Quantity =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "integer"
                    )
                TransactionDate =
                    table.Column<DateTime>(
                        nullable = false
                        ,``type`` = "timestamp without time zone"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_PalladrisTransaction", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "PalladrisTransaction"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityByDefaultColumns().HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("ProductVersion", "5.0.9")
            |> ignore

        modelBuilder.Entity("DomainModels+Palladristransaction", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .UseIdentityByDefaultColumn() |> ignore
            b.Property<string>("Pairs")
                .IsRequired(true)
                .HasColumnType("text") |> ignore
            b.Property<double>("Price")
                .IsRequired(true)
                .HasColumnType("double precision") |> ignore
            b.Property<string>("Provider")
                .IsRequired(true)
                .HasColumnType("text") |> ignore
            b.Property<int>("Quantity")
                .IsRequired(true)
                .HasColumnType("integer") |> ignore
            b.Property<DateTime>("TransactionDate")
                .IsRequired(true)
                .HasColumnType("timestamp without time zone") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("PalladrisTransaction") |> ignore

        )) |> ignore

